config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  get 'healthcheck', to: 'healthcheck#index'
  mount Sidekiq::Web, at: '/sidekiq' if Rails.env.development?

  namespace :api do
    resources :checks, only: %i[create]
  end

  scope module: :web do
    root 'welcome#index'

    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    delete 'auth/destroy', to: 'auth#destroy'
    get 'auth/failure', to: 'auth#failure'

    resources :repositories, only: %i[index new show destroy create] do
      scope module: :repositories do
        resources :checks, only: %i[show create] do
          member do
            get :output
          end
        end
      end
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/repository.rb
# frozen_string_literal: true

class Repository < ApplicationRecord
  extend Enumerize
  enumerize :language, in: %i[javascript ruby]

  belongs_to :user

  has_many :checks, dependent: :destroy
  after_destroy do |repository|
    ApplicationContainer[:repository_check_api].after_destroy_repository_cleanup(repository)
  end

  has_one :last_check, -> { order 'created_at' }, class_name: 'Repository::Check', inverse_of: :repository, dependent: nil

  validates :github_id, uniqueness: true, presence: true
end

app/models/repository/check.rb
# frozen_string_literal: true

class Repository::Check < ApplicationRecord
  include AASM

  belongs_to :repository

  aasm do
    state :running, initial: true
    state :failed, :finished

    event :fail do
      transitions from: :running, to: :failed
    end

    event :finish do
      transitions from: :running, to: :finished
    end
  end

  after_destroy do |repository_check|
    ApplicationContainer[:repository_check_api].after_destroy_cleanup(repository_check)
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  validates :email, uniqueness: true

  has_many :repositories, dependent: :destroy
end

app/controllers/api/application_controller.rb
# frozen_string_literal: true

class Api::ApplicationController < ActionController::API
end

app/controllers/api/checks_controller.rb
# frozen_string_literal: true

class Api::ChecksController < Api::ApplicationController
  # github webhook listener
  def create
    repository = Repository.find_by!(github_id: params['repository']['id'])

    RepositoryCheckJob.perform_later(repository.checks.create!)

    render json: {
      pong: params['repository']['name']
    }, status: :ok
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include AuthConcern
  include Pundit::Authorization

  rescue_from Pundit::NotAuthorizedError, with: :handle_access_denied

  def repository_check_api
    ApplicationContainer[:repository_check_api]
  end

  def octokit_client
    ApplicationContainer[:octokit_client]
  end
end

app/controllers/concerns/auth_concern.rb
# frozen_string_literal: true

module AuthConcern
  def sign_in(user)
    session[:user_id] = user.id
  end

  def sign_out
    session.delete(:user_id)
    session.clear
  end

  def signed_in?
    session[:user_id].present? && current_user.present?
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def verify_admin
    return if signed_in? && current_user.admin

    handle_access_denied
  end

  def handle_access_denied
    redirect_to root_path, alert: t('errors.access_denied')
  end

  def verify_profile
    handle_access_denied unless signed_in?
  end
end

app/controllers/healthcheck_controller.rb
# frozen_string_literal: true

class HealthcheckController < ApplicationController
  def index
    ActiveRecord::Base.connection.execute('SELECT 1')

    render plain: 'ok'
  end
end

app/controllers/web/application_controller.rb
# frozen_string_literal: true

class Web::ApplicationController < ApplicationController
end

app/controllers/web/auth_controller.rb
# frozen_string_literal: true

class Web::AuthController < Web::ApplicationController
  def callback
    user = AuthenticateUserService.new.call(request.env['omniauth.auth'])
    sign_in user

    redirect_to root_path
  end

  def failure
    redirect_to root_path, alert: t('errors.general_message')
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/web/repositories/application_controller.rb
# frozen_string_literal: true

class Web::Repositories::ApplicationController < Web::ApplicationController
  helper_method :resource_repository

  def resource_repository
    @resource_repository ||= Repository.find(params[:repository_id])
  end
end

app/controllers/web/repositories/checks_controller.rb
# frozen_string_literal: true

require 'json'

class Web::Repositories::ChecksController < Web::Repositories::ApplicationController
  before_action :set_repository_check, only: %i[show output]

  def show
    authorize @repository_check

    @check_output_exist = File.exist? repository_check_api.storage_output_path(@repository_check)
  end

  def output
    authorize @repository_check

    render inline: repository_check_api.get_output(@repository_check) # rubocop:disable Rails/RenderInline
  end

  def create
    repository_check = resource_repository.checks.build
    authorize repository_check

    repository_check.save!

    RepositoryCheckJob.perform_later(repository_check)

    redirect_to repository_check_path(resource_repository, repository_check), notice: t('repository_checks.notices.started')
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_repository_check
    @repository_check = Repository::Check.find(params[:id])
  end
end

app/controllers/web/repositories_controller.rb
# frozen_string_literal: true

class Web::RepositoriesController < Web::ApplicationController
  before_action :set_repository, only: %i[show destroy]

  def index
    authorize Repository

    @repositories = current_user.repositories.includes(:last_check)
  end

  def show
    authorize @repository
  end

  def new
    authorize Repository

    @repository = Repository.new
    @repository_options = user_repository_options
  end

  def create
    authorize Repository

    github_id = repository_params[:github_id].empty? ? nil : repository_params[:github_id].to_i
    @repository = CreateRepositoryService.new.call(current_user, github_id)

    if @repository.valid?
      redirect_to repositories_path, notice: t('repositories.notices.created')
    else
      @repository_options = user_repository_options
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @repository

    @repository.destroy!

    begin
      octokit_client.remove_hook(current_user, @repository) if @repository.hook_id.present?
    rescue Octokit::Error
      Rails.logger.error(e)
      Appsignal.set_error(e)
    end

    redirect_to repositories_url, notice: t('repositories.notices.destroyed')
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_repository
    @repository = Repository.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def repository_params
    params.require(:repository).permit(:github_id)
  end

  def user_repository_options
    @user_repository_options ||= octokit_client
                                 .repositories(current_user)
                                 .filter { |repo| Repository.language.values.include?(repo[:language]&.downcase) } # rubocop:disable Performance/InefficientHashSearch
                                 .pluck(:name, :id)
  end
end

app/controllers/web/welcome_controller.rb
# frozen_string_literal: true

class Web::WelcomeController < Web::ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include AuthConcern
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = t('app_name')
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = javascript_importmap_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  body.d-flex.flex-column.h-100
    = render 'layouts/shared/header'
    main
      .mt-4.mb-5.pb-5
        .container
          - flash.each do |type, msg|
            div class="alert alert-#{type == 'alert' ? 'danger' : 'info'}"
              - if msg.is_a?(Array)
                - msg.each do |cur_msg|
                  div = cur_msg
              - else
                = msg
          .p-4.align-items-center.border.shadow.bg-white.rounded-3
            .row
              .p-3.p-lg-5.pt-lg-0
                = yield

app/views/layouts/shared/_header.html.slim
header.container.mb-2
  .d-flex.flex-wrap.align-items-center.py-2.border-bottom
    .navbar.navbar-expand-md.navbar-light.me-auto
      = link_to t('app_name'), root_path, class: 'navbar-brand me-md-4'
      - if policy(Repository).index?
        = link_to t('repositories.index'), repositories_path, class: 'navbar-brand me-md-4'
    - if signed_in?
      div = current_user.nickname
      = button_to t('auth.sign_out'), auth_destroy_path, method: :delete, data: { turbo: false }, class: 'ms-3 btn btn-primary'
    - else
      = button_to t('auth.sign_in'), auth_request_path('github'), method: :post, data: { turbo: false }, class: 'ms-3 btn btn-primary'

app/views/layouts/shared/_headline.html.slim
.mb-4
  h2 = title
  hr

app/views/web/repositories/_form.html.slim
= simple_form_for(@repository) do |f|
  = f.input :github_id, collection: @repository_options, label: false, include_blank: t('repositories.form.select_placeholder'), input_html: { class: 'mt-3' }
  = f.button :submit, t('repositories.actions.create'), class: 'btn-primary mt-3'

app/views/web/repositories/checks/show.html.slim
h2 = t('repository_checks.show')

table.table
  tbody
    tr
      td = Repository::Check.human_attribute_name(:created_at)
      td = @repository_check.created_at.strftime('%F %T')
    tr
      td = Repository::Check.human_attribute_name(:state)
      td = @repository_check.aasm.human_state
    tr
      td = t('repository_checks.attributes.passed?')
      td = @repository_check.passed
    tr
      td = t('repository_checks.attributes.repository')
      td = link_to @repository_check.repository.full_name, @repository_check.repository
    tr
      td = t('repository_checks.attributes.sha')
      td
        a target="_blank" rel="noopener" href="https://github.com/#{@repository_check.repository.full_name}/commit/#{@repository_check.commit}"
          = @repository_check.commit
    - if @check_output_exist
      tr
        td = t('repository_checks.offences')
        td
          = link_to t('repository_checks.actions.full_report'), output_repository_check_path(@repository_check.repository, @repository_check), target: '_blank', rel: 'noopener'

app/views/web/repositories/index.html.slim
.d-flex.justify-content-between.align-items-center
  h1 = t('repositories.index')
  = link_to t('repositories.new'), new_repository_path, class: 'btn btn-primary'

table.table.table-striped.table-hover.mt-4
  thead
    tr
      th scope="col" = Repository.human_attribute_name(:name)
      th scope="col" = Repository.human_attribute_name(:language)
      th scope="col" = t('repositories.last_check_status')
  tbody
    - @repositories.each do |repository|
      tr
        td = link_to repository.name, repository
        td = repository.language
        td = repository.last_check&.passed

app/views/web/repositories/new.html.slim
h1 = t('repositories.new')

== render 'form', repository: @repository

app/views/web/repositories/show.html.slim
h2 = t('repositories.show')

div
  strong.me-2 = "#{Repository.human_attribute_name(:full_name)}:"
  = @repository.full_name
div
  strong.me-2 = "#{Repository.human_attribute_name(:language)}:"
  = @repository.language
div
  strong.me-2 = "#{Repository.human_attribute_name(:created_at)}:"
  = @repository.created_at.strftime('%F %T')
div
  strong.me-2 = "#{Repository.human_attribute_name(:updated_at)}:"
  = @repository.updated_at.strftime('%F %T')

.d-flex.mt-3
  = button_to t('repositories.actions.check'), repository_checks_path(@repository), method: :post, class: 'btn btn-primary me-3'
  = button_to t('repositories.actions.destroy'), @repository, method: :delete, class: 'btn btn-danger', form: { data: { turbo_confirm: t('confirmations.delete') } }

hr

h3.mt-5 = "#{t('repository_checks.index')}:"
table.table.table-striped
  thead
    tr
      th scope="col" #
      th scope="col" = Repository::Check.human_attribute_name(:state)
      th scope="col" = t('repository_checks.attributes.sha')
      th scope="col" = t('repository_checks.attributes.passed?')
      th scope="col" = Repository::Check.human_attribute_name(:created_at)
  tbody
    - @repository.checks.each do |check|
      tr
        td scope="row"
          = link_to check.id, repository_check_path(@repository, check)
        td scope="row"
          = check.aasm.human_state
        td scope="row"
          a target="_blank" rel="noopener" href="https://github.com/#{@repository.full_name}/commit/#{check.commit}"
            = check.commit
        td scope="row"
          = check.passed
        td scope="row"
          = check.created_at.strftime('%F %T')

app/views/web/welcome/index.html.slim
h2 = t('welcome_message', app_name: t('app_name'))